Traceback (most recent call last):
  File "/Users/brunamoura/anaconda3/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/brunamoura/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brunamoura/anaconda3/lib/python3.11/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brunamoura/anaconda3/lib/python3.11/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brunamoura/anaconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/brunamoura/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/brunamoura/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/brunamoura/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#Excluir colunas que tenham mais do que 5% de dados ausentes
colunas_mantidas = df_na_counts[df_na_counts['% de dados ausentes'] < 5]['VariÃ¡vel']
df_eventos = df_eventos[colunas_mantidas]
print(df_eventos.columns)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[5], line 2[0m
[1;32m      1[0m [38;5;66;03m#Excluir colunas que tenham mais do que 5% de dados ausentes[39;00m
[0;32m----> 2[0m colunas_mantidas [38;5;241m=[39m df_na_counts[df_na_counts[[38;5;124m'[39m[38;5;132;01m% d[39;00m[38;5;124me dados ausentes[39m[38;5;124m'[39m] [38;5;241m<[39m [38;5;241m5[39m][[38;5;124m'[39m[38;5;124mVariÃ¡vel[39m[38;5;124m'[39m]
[1;32m      3[0m df_eventos [38;5;241m=[39m df_eventos[colunas_mantidas]
[1;32m      4[0m [38;5;28mprint[39m(df_eventos[38;5;241m.[39mcolumns)

[0;31mNameError[0m: name 'df_na_counts' is not defined
NameError: name 'df_na_counts' is not defined

